---
- hosts: jenkins_master
  become: true  #become a root user to install packages
  tasks:
    - name: add jenkins key
      apt_key:  #module used for key
        url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present 

    - name: add jenkins repository
      apt_repository:  #module used for repository
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present  

    - name: install java
      apt: #module used for package installation
        name: openjdk-11-jre  
        state: present  

    - name: install jenkins
      apt:  #module used for package installation
        name: jenkins  
        state: present  

    - name: start jenkins service
      service:  #module used for service management 
        name: jenkins  
        state: started  
        
    - name: enable jenkins to start at boot time
      service:  #module used for service management
        name: jenkins  
        enabled: yes  